// @AI_GENERATED
package cli

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

// onboardConfig holds all values collected during the interactive onboard flow.
type onboardConfig struct {
	// Database
	DBHost     string
	DBPort     int
	DBUser     string
	DBPassword string
	DBName     string
	DBSSLMode  string

	// Redis
	RedisAddr     string
	RedisPassword string
	RedisDB       int

	// JWT
	JWTSecret string

	// Model Provider
	ModelProvider string
	ModelAPIKey   string
}

// configTemplate is the YAML template written to configs/config.yaml.
const configTemplate = `# Generated by openclaw onboard
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s

database:
  host: "{{ .DBHost }}"
  port: {{ .DBPort }}
  user: "{{ .DBUser }}"
  password: "{{ .DBPassword }}"
  dbname: "{{ .DBName }}"
  sslmode: "{{ .DBSSLMode }}"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h

redis:
  addr: "{{ .RedisAddr }}"
  password: "{{ .RedisPassword }}"
  db: {{ .RedisDB }}

jwt:
  secret: "{{ .JWTSecret }}"
  access_token_ttl: 24h
  refresh_token_ttl: 168h

log:
  level: "info"
  format: "console"

migration:
  enabled: true
  source_type: "filesystem"
  source_path: "./migrations"
  lock_timeout: 30s
  table_name: "schema_migrations"

model:
  provider: "{{ .ModelProvider }}"
  api_key: "{{ .ModelAPIKey }}"
`

// NewOnboardCommand creates the "openclaw onboard" command.
func NewOnboardCommand() *cobra.Command {
	var configPath string
	var outputPath string

	cmd := &cobra.Command{
		Use:   "onboard",
		Short: "Interactive setup wizard for OpenClaw",
		Long:  "Interactively guide you through database, Redis, JWT, and model provider configuration, then generate configs/config.yaml.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runOnboard(configPath, outputPath)
		},
	}

	cmd.Flags().StringVar(&configPath, "config", "configs/config.yaml", "path to configuration file (used by doctor after onboard)")
	cmd.Flags().StringVar(&outputPath, "output", "configs/config.yaml", "path to write the generated config file")

	return cmd
}

// runOnboard drives the interactive onboard flow.
func runOnboard(configPath, outputPath string) error {
	scanner := bufio.NewScanner(os.Stdin)

	fmt.Printf("\n%s%sOpenClaw Onboard Wizard%s\n\n", colorBold, colorGreen, colorReset)
	fmt.Println("Press Enter to accept the default value shown in [brackets].")
	fmt.Println()

	cfg := &onboardConfig{}

	// ── Database ──────────────────────────────────────────────────────────────
	fmt.Printf("%s%s[1/4] Database Configuration%s\n", colorBold, colorYellow, colorReset)

	cfg.DBHost = prompt(scanner, "  Host", "localhost")
	portStr := prompt(scanner, "  Port", "5432")
	port, err := strconv.Atoi(portStr)
	if err != nil || port <= 0 {
		port = 5432
	}
	cfg.DBPort = port
	cfg.DBUser = prompt(scanner, "  User", "openclaw")
	cfg.DBPassword = prompt(scanner, "  Password", "openclaw")
	cfg.DBName = prompt(scanner, "  Database name", "openclaw")
	cfg.DBSSLMode = promptChoice(scanner, "  SSL mode", []string{"disable", "require", "verify-full"}, "disable")

	fmt.Println()

	// ── Redis ─────────────────────────────────────────────────────────────────
	fmt.Printf("%s%s[2/4] Redis Configuration%s\n", colorBold, colorYellow, colorReset)

	cfg.RedisAddr = prompt(scanner, "  Address (host:port)", "localhost:6379")
	cfg.RedisPassword = prompt(scanner, "  Password (leave empty for none)", "")
	redisDBStr := prompt(scanner, "  DB index", "0")
	redisDB, err := strconv.Atoi(redisDBStr)
	if err != nil || redisDB < 0 {
		redisDB = 0
	}
	cfg.RedisDB = redisDB

	fmt.Println()

	// ── JWT ───────────────────────────────────────────────────────────────────
	fmt.Printf("%s%s[3/4] JWT Configuration%s\n", colorBold, colorYellow, colorReset)

	cfg.JWTSecret = prompt(scanner, "  Secret key", "change-me-in-production")

	fmt.Println()

	// ── Model Provider ────────────────────────────────────────────────────────
	fmt.Printf("%s%s[4/4] Model Provider%s\n", colorBold, colorYellow, colorReset)

	cfg.ModelProvider = promptChoice(scanner, "  Provider", []string{"openai", "anthropic", "gemini", "ollama", "groq", "mistral"}, "openai")
	if cfg.ModelProvider == "ollama" {
		cfg.ModelAPIKey = prompt(scanner, "  API key (not required for Ollama, press Enter to skip)", "")
	} else {
		cfg.ModelAPIKey = prompt(scanner, "  API key", "")
	}

	fmt.Println()

	// ── Generate config.yaml ──────────────────────────────────────────────────
	if err := writeConfig(cfg, outputPath); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	fmt.Printf("%s✓%s  Config written to %s\n\n", colorGreen, colorReset, outputPath)

	// ── Run doctor ────────────────────────────────────────────────────────────
	fmt.Printf("%s%sRunning doctor to validate configuration…%s\n\n", colorBold, colorGreen, colorReset)

	return runDoctor(configPath)
}

// prompt prints a question with a default value and reads one line from the scanner.
// If the user presses Enter without input, the default is returned.
func prompt(scanner *bufio.Scanner, question, defaultVal string) string {
	if defaultVal != "" {
		fmt.Printf("%s [%s]: ", question, defaultVal)
	} else {
		fmt.Printf("%s: ", question)
	}

	if scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line != "" {
			return line
		}
	}
	return defaultVal
}

// promptChoice shows a list of valid choices and loops until the user picks one.
func promptChoice(scanner *bufio.Scanner, question string, choices []string, defaultVal string) string {
	choiceStr := strings.Join(choices, "/")
	for {
		fmt.Printf("%s (%s) [%s]: ", question, choiceStr, defaultVal)

		if scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())
			if line == "" {
				return defaultVal
			}
			for _, c := range choices {
				if strings.EqualFold(line, c) {
					return c
				}
			}
			fmt.Printf("  %s✗%s  Invalid choice. Please enter one of: %s\n", colorRed, colorReset, choiceStr)
		} else {
			return defaultVal
		}
	}
}

// writeConfig renders the config template and writes it to outputPath.
func writeConfig(cfg *onboardConfig, outputPath string) error {
	tmpl, err := template.New("config").Parse(configTemplate)
	if err != nil {
		return fmt.Errorf("template parse error: %w", err)
	}

	f, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("cannot create file %s: %w", outputPath, err)
	}
	defer f.Close()

	return tmpl.Execute(f, cfg)
}

// @AI_GENERATED: end
