/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline-variant': '#464554',
        'error-container': '#93000a',
        'error': '#ffb4ab',
        'tertiary-container': '#00885d',
        'surface': '#0b1326',
        'on-surface-variant': '#c7c4d7',
        'surface-container-high': '#222a3d',
        'surface-container': '#171f33',
        'surface-variant': '#2d3449',
        'tertiary': '#4edea3',
        'secondary': '#4cd7f6',
        'surface-tint': '#c0c1ff',
        'surface-container-low': '#131b2e',
        'on-background': '#dae2fd',
        'on-error-container': '#ffdad6',
        'primary-container': '#8083ff',
        'secondary-container': '#03b5d3',
        'surface-container-lowest': '#060e20',
        'outline': '#908fa0',
        'on-surface': '#dae2fd',
        'surface-container-highest': '#2d3449',
        'primary': '#c0c1ff',
        'on-primary': '#1000a9',
        'on-tertiary': '#003824',
        'on-secondary': '#003640',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
